@APP.factory "I18n", ->

  translations:
    ca:
      "Save changes": "Desar"
      "New service": "Nou servei"
      "Cancel": "Cancel·la"
      "no parent": "Sense pare"
      "Welcome to the new-generation time banking system": "Benvingut al nou sistema de Banc de Temps"
      "Learn more": "Saber-ne més"
      "New organization": "Nou Banc"
      "Name": "Nom"
      "Organization": "Banc de Temps"
      "E-mail": "Correu electrònic"
      "Administrator": "Administrador"
      "Super Administrator": "Administrador de sistema"
      "Member Code": "Códi de membre"
      "Register date": "Data d'alta"
      "Document ID": "Número de document"
      "Phones": "Telèfons"
      "Offers categories": "Serveis ofertats"
      "New user": "Nou usuari"
      "Edit": "Modificar"
      "Password": "Contrasenya"
      "Repeat password": "Repetir contranseya"
      "Birth date": "Data de neixement"
      "Phone": "Telèfon"
      "Alternate Phone": "Telèfon alternatiu"
      "Categories": "Serveis"
      "Users": "Usuaris"
      "By user": "Per usuaris"
      "By category": "Per serveis"
      "Category": "Categoria"
      "Members": "Membres"
      "View": "Veure"
      
    es:
      "Save changes": "Guardar"
      "New service": "Nuevo servicio"
      "Cancel": "Cancelar"
      "no parent": "Sin padre"
      "Welcome to the new-generation time banking system": "Bienvenido al nuevo sistema de Bancos de Tiempo" 
      "Learn more": "Saber más"
      "New organization": "Nuevo Banco"
      "Name": "Nombre"
      "Organization": "Banco de Tiempo"
      "E-mail": "Correo electrónico"
      "Administrator": "Administrador"
      "Super Administrator": "Administrador de sistema"
      "Member Code": "Código de miembro"
      "Register date": "Fecha de alta"
      "Document ID": "Número de documento"
      "Phones": "Teléfonos"
      "Offers categories": "Servicios ofrecidos"
      "New user": "Nuevo usuario"
      "Edit": "Modificar"
      "Password": "Contraseña"
      "Repeat password": "Repetir contraña"
      "Birth date": "Fecha de nacimiento"
      "Phone": "Teléfono"
      "Alternate Phone": "Teléfono alternativo"
      "Categories": "Servicios"
      "Users": "Usuarios"
      "By user": "Por usuarios"
      "By category": "Por servicios"
      "Category": "Categoría"
      "Members": "Miembros"
      "View": "Ver"

  t: (word) ->
    currentLanguage = "es"
    translations[currentLanguage]?[word] ? word

